### ISSUE TITLE
无法签到领京豆

### ISSUE THREAD

**Issue by Book-fall2wish** [shufflewzc/faker4#2]
重新拉取了库也还是这样，CK没失效

领京豆签到 | task shufflewzc_faker4_main/jd_signbeanact.js

## 开始执行... 2024-05-25 13:11:58

🔔领京豆签到, 开始!

====================共1个京东账号Cookie=================

============脚本执行时间：2024/05/25 13:11:59=============

>>>>>>>>>>>>>>Faker提醒您：有问题先更新 关注频道https://t.me/scriptalking>>>>>>>>>>>>>>>

*****开始【京东账号1】****

DEBUG2:"{\n  \"code\": \"402\",\n  \"message\": \"活动现在挤不进去呀，待会再来试试吧\"\n}"

🔔领京豆签到, 结束! 🕛 5.865 秒

## 执行结束... 2024-05-25 13:12:05  耗时 7 秒

**Comment by dover** [comment]
+1

**Comment by shufflewzc** [comment]
脚本失效 已删除
